GET http://localhost:8000/api/users
Content-Type: application/json
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvbGV0ZXgiLCJpYXQiOjE2NTMwNjAzMTMsImV4cCI6MTY1MzA2MDM0M30.2r-oH49CE6ivDjdSH_JcK0LTkKo2irjdzLmtYBNEULU

{"token" : ""}